---
-  hosts: lxcroot
   become: false
   tasks:

    - name: copy default html file 
      tags: always
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
