---

- hosts: all
  tasks:

  - name: install apache and php packages for all dist
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    
  
